export interface IconConfig {
  id: string;
  name: string;
  width: number;
  height: number;
  type: 'image/png' | 'image/x-icon' | 'image/svg+xml';
  rel?: string;
  usage: string;
  description: string; // Detailed explanation
  learnMoreUrl?: string; // Optional link to documentation
  htmlTemplate: (url: string) => string;
  transparent?: boolean;
}

export const ICON_DEFINITIONS: IconConfig[] = [
  {
    id: 'favicon-16',
    name: 'favicon-16x16.png',
    width: 16,
    height: 16,
    type: 'image/png',
    rel: 'icon',
    usage: 'Browser tab icon (small)',
    description: 'The 16x16 favicon appears in browser tabs, bookmarks, and address bars. This smaller size is used when space is limited, such as in browser tab lists or bookmark menus. Modern browsers will scale this icon as needed, but providing a dedicated 16x16 version ensures optimal clarity at small sizes.',
    learnMoreUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#icon',
    htmlTemplate: (url) => `<link rel="icon" type="image/png" sizes="16x16" href="${url}" />`,
    transparent: true,
  },
  {
    id: 'favicon-32',
    name: 'favicon-32x32.png',
    width: 32,
    height: 32,
    type: 'image/png',
    rel: 'icon',
    usage: 'Browser tab icon (standard)',
    description: 'The 32x32 favicon is the standard size for browser tabs and bookmarks on most desktop browsers. This is the most commonly displayed favicon size and should be your primary focus for visual clarity. It appears in browser tabs, bookmark bars, and history lists across Chrome, Firefox, Safari, and Edge.',
    learnMoreUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#icon',
    htmlTemplate: (url) => `<link rel="icon" type="image/png" sizes="32x32" href="${url}" />`,
    transparent: true,
  },
  {
    id: 'favicon-16-dark',
    name: 'favicon-16x16-dark.png',
    width: 16,
    height: 16,
    type: 'image/png',
    rel: 'icon',
    usage: 'Browser tab icon (small) - Dark Mode',
    description: 'This is the dark mode variant of the 16x16 favicon. Modern browsers that support the prefers-color-scheme media query will automatically use this icon when the user has dark mode enabled. The icon uses a light/white color scheme to ensure visibility against dark browser UI elements.',
    learnMoreUrl: 'https://web.dev/articles/building/an-adaptive-favicon',
    htmlTemplate: (url) => `<link rel="icon" type="image/png" sizes="16x16" href="${url}" media="(prefers-color-scheme: dark)" />`,
    transparent: true,
  },
  {
    id: 'favicon-32-dark',
    name: 'favicon-32x32-dark.png',
    width: 32,
    height: 32,
    type: 'image/png',
    rel: 'icon',
    usage: 'Browser tab icon (standard) - Dark Mode',
    description: 'The dark mode variant of the standard 32x32 favicon. Browsers with dark mode support will display this icon instead of the regular favicon when the user has enabled dark mode. This ensures your favicon remains visible and aesthetically consistent with the dark browser interface.',
    learnMoreUrl: 'https://web.dev/articles/building/an-adaptive-favicon',
    htmlTemplate: (url) => `<link rel="icon" type="image/png" sizes="32x32" href="${url}" media="(prefers-color-scheme: dark)" />`,
    transparent: true,
  },
  {
    id: 'apple-touch-icon',
    name: 'apple-touch-icon.png',
    width: 180,
    height: 180,
    type: 'image/png',
    rel: 'apple-touch-icon',
    usage: 'iOS Home Screen',
    description: 'The Apple Touch Icon is used when users add your website to their iOS home screen. iOS automatically applies rounded corners and a subtle shadow effect, so your icon should be a simple square with no transparency. The 180x180 size supports all modern iOS devices including iPhones and iPads with Retina displays.',
    learnMoreUrl: 'https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html',
    htmlTemplate: (url) => `<link rel="apple-touch-icon" sizes="180x180" href="${url}" />`,
    transparent: false,
  },
  {
    id: 'android-chrome-192',
    name: 'android-chrome-192x192.png',
    width: 192,
    height: 192,
    type: 'image/png',
    usage: 'Android Home Screen',
    description: 'This icon appears when Android users add your website to their home screen. It should be referenced in your web app manifest file (manifest.json). The 192x192 size is the minimum recommended size for Android home screen icons and ensures good quality on most Android devices.',
    learnMoreUrl: 'https://developer.mozilla.org/en-US/docs/Web/Manifest',
    htmlTemplate: (url) => `<!-- Referenced in manifest.json -->\n{ "src": "${url}", "sizes": "192x192", "type": "image/png" }`,
    transparent: true,
  },
  {
    id: 'android-chrome-512',
    name: 'android-chrome-512x512.png',
    width: 512,
    height: 512,
    type: 'image/png',
    usage: 'Android Splash Screen / PWA',
    description: 'The 512x512 icon is used for Progressive Web Apps (PWA) and Android splash screens. This larger size ensures your icon looks sharp on high-resolution devices and when displayed at larger sizes, such as in the Android app drawer or during PWA installation. This should also be referenced in your manifest.json file.',
    learnMoreUrl: 'https://web.dev/articles/add-manifest',
    htmlTemplate: (url) => `<!-- Referenced in manifest.json -->\n{ "src": "${url}", "sizes": "512x512", "type": "image/png" }`,
    transparent: true,
  },
  {
    id: 'safari-pinned-tab',
    name: 'safari-pinned-tab.svg',
    width: 512, // Standard size for display purposes
    height: 512,
    type: 'image/svg+xml',
    rel: 'mask-icon',
    usage: 'Safari Pinned Tab',
    description: 'This monochrome SVG icon is used when users pin your tab in Safari. It must be a single color (usually black) with a transparent background. The "color" attribute in the link tag defines the hover/active color.',
    learnMoreUrl: 'https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html',
    htmlTemplate: (url) => `<link rel="mask-icon" href="${url}" color="#5bbad5" />`,
    transparent: true,
  },
  {
    id: 'mstile-70',
    name: 'mstile-70x70.png',
    width: 70,
    height: 70,
    type: 'image/png',
    usage: 'Windows Small Tile',
    description: 'Small tile for Windows Start Menu.',
    learnMoreUrl: 'https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn255024(v=vs.85)',
    htmlTemplate: (url) => `<meta name="msapplication-square70x70logo" content="${url}" />`,
    transparent: true,
  },
  {
    id: 'mstile-150',
    name: 'mstile-150x150.png',
    width: 150,
    height: 150,
    type: 'image/png',
    usage: 'Windows Medium Tile',
    description: 'The MS Tile icon appears when users pin your website to the Windows Start Menu. This is specific to Windows devices and Internet Explorer/Edge browsers. The 150x150 size is the standard for medium-sized tiles. You can customize the tile background color using the msapplication-TileColor meta tag.',
    learnMoreUrl: 'https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn255024(v=vs.85)',
    htmlTemplate: (url) => `<meta name="msapplication-TileImage" content="${url}" />`,
    transparent: true,
  },
  {
    id: 'mstile-310x150',
    name: 'mstile-310x150.png',
    width: 310,
    height: 150,
    type: 'image/png',
    usage: 'Windows Wide Tile',
    description: 'Wide tile for Windows Start Menu.',
    learnMoreUrl: 'https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn255024(v=vs.85)',
    htmlTemplate: (url) => `<meta name="msapplication-wide310x150logo" content="${url}" />`,
    transparent: true,
  },
  {
    id: 'mstile-310',
    name: 'mstile-310x310.png',
    width: 310,
    height: 310,
    type: 'image/png',
    usage: 'Windows Large Tile',
    description: 'Large tile for Windows Start Menu.',
    learnMoreUrl: 'https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn255024(v=vs.85)',
    htmlTemplate: (url) => `<meta name="msapplication-square310x310logo" content="${url}" />`,
    transparent: true,
  },
  {
    id: 'twitter-card',
    name: 'twitter-card.png',
    width: 1200,
    height: 600,
    type: 'image/png',
    usage: 'Twitter Card Image',
    description: 'Optimized image for Twitter sharing cards. While Twitter often supports Open Graph images, providing a dedicated 2:1 aspect ratio image ensures the best presentation in Twitter feeds.',
    learnMoreUrl: 'https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image',
    htmlTemplate: (url) => `<meta name="twitter:image" content="${url}" />`,
    transparent: false,
  },
  {
    id: 'og-image',
    name: 'og-image.png',
    width: 1200,
    height: 630,
    type: 'image/png',
    usage: 'Social Media Preview (Open Graph)',
    description: 'The Open Graph image is displayed when your website is shared on social media platforms like Facebook, LinkedIn, and Slack. The 1200x630 aspect ratio (1.91:1) is recommended by Facebook and works well across most platforms. This image should be visually compelling and include your logo or branding to make your shared links stand out.',
    learnMoreUrl: 'https://ogp.me/',
    htmlTemplate: (url) => `<meta property="og:image" content="${url}" />`,
    transparent: false,
  },
];
